#docker-compose.yml

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - JWT_SECRET=test-secret-for-env

  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
